// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3tG4g7FXAslaNkeCUtVyWRbeLXOEWlhk',
    appId: '1:664928552827:web:8ca838a2cb4591cc22dfde',
    messagingSenderId: '664928552827',
    projectId: 'basictiktokflutterrr',
    authDomain: 'basictiktokflutterrr.firebaseapp.com',
    storageBucket: 'basictiktokflutterrr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp94xfQOEh3qG2TYArM1MxEUg4LvVfYeA',
    appId: '1:664928552827:android:c5e994e1ebf0521722dfde',
    messagingSenderId: '664928552827',
    projectId: 'basictiktokflutterrr',
    storageBucket: 'basictiktokflutterrr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnyqkkLn_kKdU7lA6QCJLrT9cPS8A1tq8',
    appId: '1:664928552827:ios:a9193212c35835ee22dfde',
    messagingSenderId: '664928552827',
    projectId: 'basictiktokflutterrr',
    storageBucket: 'basictiktokflutterrr.firebasestorage.app',
    iosBundleId: 'com.kenant42.mytiktokcloneapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnyqkkLn_kKdU7lA6QCJLrT9cPS8A1tq8',
    appId: '1:664928552827:ios:a9193212c35835ee22dfde',
    messagingSenderId: '664928552827',
    projectId: 'basictiktokflutterrr',
    storageBucket: 'basictiktokflutterrr.firebasestorage.app',
    iosBundleId: 'com.kenant42.mytiktokcloneapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3tG4g7FXAslaNkeCUtVyWRbeLXOEWlhk',
    appId: '1:664928552827:web:5021c0b7ef68080322dfde',
    messagingSenderId: '664928552827',
    projectId: 'basictiktokflutterrr',
    authDomain: 'basictiktokflutterrr.firebaseapp.com',
    storageBucket: 'basictiktokflutterrr.firebasestorage.app',
  );
}
